version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
  build:
    commands:
      - echo Building the Go code...
      - go build application.go 
artifacts: s3://codepipeline-ap-south-1-430929889629/Mydemoapp/
  secondary-artifacts:
    golang_artifacts:
      base-directory: justnew
      files:
        - avg